Use `go install` instead of `go get`
Calling `go get` was causing `mage check` to fail with:
```
go: modules disabled by GO111MODULE=off; see 'go help modules'
Error: running "go get github.com/elastic/go-licenser@latest" failed with exit code 1
```

This commit fixes it by using `go install` instead.